spring:
  application:
    name: fzf-activity
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://localhost:3306/cbc_marketing?characterEncoding=UTF8&socketTimeout=60000&allowMultiQueries=true&useSSL=true
      username: root
      password: fzf917
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  task:
    scheduling:
      pool:
        size: 10

server:
  port: 8819
mybatis:
  mapper-locations: classpath*:mapper/mysql/*.xml
  config-location: classpath:mybatis-config.xml

socket:
  port: 10004
  idleTime: 30000
  lvMessageLengthSize: 6

file:
  filePath: /Users/fanzhenfeng/tmp
  fileName: test.csv






